
name: 🦄 Commit History
on:
  schedule:
    - cron: '50 23 * * *' # Run every evening, before midnight
  workflow_dispatch: # Or when it's manually triggered
jobs:
  gadpp_job:
    runs-on: ubuntu-latest
    name: Update GitHub Profile Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GADPP
        uses: umutphp/github-action-dynamic-profile-page@v2
        id: gadpp
        env:
          API_TOKEN_GITHUB: ${{ secrets.BOT_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-username: 'lissy93'
          user-email: 'alicia-gh-bot@mail.as93.net'
          readme-file: 'COMMIT-HISTORY.md'
