  
name: 📚 Generate Tech Stack

on:
  workflow_dispatch: # Manual dispatch
  push:
    branches: [ master ]
    paths: [ assets/stack.yml ]
    
jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gleich/profile_stack@master
        with:
          path: assets/stack.yml
